"""
Visualize a neighborhood at a specific pipeline stage.

Reproducibility: every figure in the project's papers and docs is
generated by this script with a pinned --stage. To regenerate a figure,
run the exact same command.

Examples:
    # List all available stages
    python scripts/visualize_neighborhood.py --list-stages

    # Day 2 figure: buildings only
    python scripts/visualize_neighborhood.py \
        --lat 47.6097 --lon -122.3331 --stage osm

    # Day 3 figure: buildings + Mapillary
    python scripts/visualize_neighborhood.py \
        --lat 47.6097 --lon -122.3331 --stage mapillary

    # Save to PNG for paper inclusion
    python scripts/visualize_neighborhood.py \
        --lat 47.6097 --lon -122.3331 --stage mapillary \
        --out docs/figures/dlr_r150_mapillary.png
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import matplotlib.pyplot as plt

from atmosphere.stages import (
    STAGE_ORDER,
    STAGE_REGISTRY,
    StageData,
    get_stages_up_to,
    list_stages,
)
from atmosphere.viz import apply_frame


def _cmd_list_stages() -> None:
    """Print all registered stages, in order, with descriptions."""
    print("Available stages (in pipeline order):\n")
    for name, desc in list_stages():
        print(f"  {name:<12} — {desc}")
    print()


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument("--list-stages", action="store_true",
                        help="List available stages and exit")

    parser.add_argument("--lat", type=float,
                        help="Query center latitude (degrees)")
    parser.add_argument("--lon", type=float,
                        help="Query center longitude (degrees)")
    parser.add_argument("--radius", type=float, default=150.0,
                        help="Query radius in meters (default 150)")

    parser.add_argument(
        "--stage", type=str, default=STAGE_ORDER[-1],
        choices=STAGE_ORDER,
        help=(
            f"Which pipeline stage to render up to (default: {STAGE_ORDER[-1]}). "
            f"Each stage includes all earlier stages."
        ),
    )

    parser.add_argument("--out", type=Path, default=None,
                        help="If set, save figure to this path (PNG). "
                             "If not set, display interactively.")

    # Stage-specific options
    parser.add_argument("--mapillary-limit", type=int, default=100,
                        help="Target image count after farthest-point sampling")
    parser.add_argument("--no-download", action="store_true",
                        help="Skip thumbnail downloads (mapillary stage only)")
    parser.add_argument("--no-cache", action="store_true",
                        help="Force re-fetch from all APIs")

    parser.add_argument("--title", type=str, default=None)
    parser.add_argument("--verbose", "-v", action="store_true")

    args = parser.parse_args()

    # --- Handle --list-stages and exit ---
    if args.list_stages:
        _cmd_list_stages()
        return 0

    # Lat/lon are required for all other invocations
    if args.lat is None or args.lon is None:
        parser.error("--lat and --lon are required unless --list-stages is given")

    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(levelname)s: %(message)s",
    )

    # --- Build the stage chain ---
    stages = get_stages_up_to(args.stage)
    logging.info(
        "Running %d stage(s) up to '%s': %s",
        len(stages), args.stage, ", ".join(s.name for s in stages),
    )

    # --- Gather common options for all stages ---
    stage_opts = {
        "use_cache": not args.no_cache,
        "mapillary_limit": args.mapillary_limit,
        "download_thumbnails": not args.no_download,
    }

    # --- Run fetch for each stage in order ---
    data = StageData()
    for stage in stages:
        logging.info("Fetching stage: %s", stage.name)
        stage.fetch(args.lat, args.lon, args.radius, data, **stage_opts)

    # --- Plot each layer ---
    fig, ax = plt.subplots(figsize=(9, 9))
    for stage in stages:
        stage.plot(data, ax)

    # --- Common frame / legend / title ---
    title = args.title or (
        f"Stage: {args.stage}  ·  ({args.lat:.4f}, {args.lon:.4f})  ·  "
        f"r={args.radius:.0f} m"
    )
    apply_frame(
        ax,
        radius_m=args.radius,
        title=title,
        buildings=data.buildings,
        images=data.mapillary_images,
    )

    # --- Output ---
    plt.tight_layout()
    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.out, dpi=150, bbox_inches="tight")
        print(f"Saved figure to {args.out}")
    else:
        plt.show()

    return 0


if __name__ == "__main__":
    sys.exit(main())