"""
Stage-based visualization for reproducible figure generation.

A "stage" represents one layer of the Atmosphere data pipeline: OSM
buildings, Mapillary imagery, aligned cameras, rendered depth, generated
scenes, and so on. Each stage is additive — drawing a later stage draws
everything from earlier stages beneath it.

This exists primarily for paper reproducibility. When writing a paper
section like "§3.1 Geometric priors from OSM", the accompanying figure
is generated by `--stage osm`. The next section's figure uses
`--stage mapillary`, and so on. A single command-line argument pins
down exactly which snapshot of the pipeline a figure represents.

Adding a new stage:
    1. Subclass Stage, implement fetch() and plot() (and maybe add_cli_args()).
    2. Register it in STAGE_REGISTRY below with a short, memorable key.
    3. List it in the right order (earlier stages first).

The registry is deliberately a plain dict at module scope, not a plugin
system. We are in a research project — one person, one repo, one set
of stages. Over-engineering the registry would slow us down with no
corresponding benefit.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from matplotlib.axes import Axes

from atmosphere.retrieval.buildings import Building, fetch_buildings
from atmosphere.retrieval.mapillary import MapillaryImage, fetch_mapillary_images


# -----------------------------------------------------------------------------
# Stage data container
# -----------------------------------------------------------------------------


@dataclass
class StageData:
    """
    Carries the data produced by every stage run so far, cumulatively.

    Each stage's fetch() reads fields populated by earlier stages (if
    needed) and writes its own field. Later stages see everything.

    We use a mutable dataclass here (not frozen) on purpose: stages
    populate it in sequence, and the alternative (returning a new dataclass
    per stage) would be more verbose without clear benefit at this scale.
    """

    # Geometry layer (stage: osm)
    buildings: list[Building] = field(default_factory=list)

    # Street-level imagery layer (stage: mapillary)
    mapillary_images: list[MapillaryImage] = field(default_factory=list)

    # Future stages will add fields here. Examples of what's coming:
    #   aligned_cameras: list[AlignedCamera] = ...     (Week 3)
    #   depth_render: CanonicalRender | None = None    (Week 2)
    #   generated_scene: GeneratedScene | None = None  (Phase 2)


# -----------------------------------------------------------------------------
# Base Stage class
# -----------------------------------------------------------------------------


class Stage(ABC):
    """
    A single layer in the visualization pipeline.

    Subclasses must set `name` and `description`, and implement both
    `fetch` (to populate StageData) and `plot` (to draw this layer
    onto a matplotlib Axes).
    """

    name: str = ""          # e.g., "osm"
    description: str = ""   # human-readable, shown in --list-stages

    @abstractmethod
    def fetch(
        self,
        lat: float,
        lon: float,
        radius_m: float,
        data: StageData,
        **opts: Any,
    ) -> None:
        """
        Populate `data` with this stage's outputs.

        Read-only access to fields populated by earlier stages is fine;
        writes should go only to this stage's own field(s). Stages should
        be idempotent — calling fetch() twice with the same inputs should
        produce the same result and not corrupt state.
        """
        ...

    @abstractmethod
    def plot(self, data: StageData, ax: Axes) -> None:
        """
        Render this stage's layer onto `ax`. Earlier stages are drawn
        first (by the pipeline runner); this method adds on top.
        """
        ...


# -----------------------------------------------------------------------------
# Concrete stages
# -----------------------------------------------------------------------------


class OSMStage(Stage):
    name = "osm"
    description = (
        "Building footprints from OpenStreetMap, colored by height provenance. "
        "This is the 'geometric priors' layer."
    )

    def fetch(
        self,
        lat: float,
        lon: float,
        radius_m: float,
        data: StageData,
        **opts: Any,
    ) -> None:
        data.buildings = fetch_buildings(
            lat=lat,
            lon=lon,
            radius_m=radius_m,
            use_cache=opts.get("use_cache", True),
        )

    def plot(self, data: StageData, ax: Axes) -> None:
        from atmosphere.viz import plot_buildings
        plot_buildings(data.buildings, ax)


class MapillaryStage(Stage):
    name = "mapillary"
    description = (
        "Street-level imagery positions and heading from Mapillary, overlaid "
        "on the OSM layer. This is the 'visual references' layer."
    )

    def fetch(
        self,
        lat: float,
        lon: float,
        radius_m: float,
        data: StageData,
        **opts: Any,
    ) -> None:
        data.mapillary_images = fetch_mapillary_images(
            lat=lat,
            lon=lon,
            radius_m=radius_m,
            target_count=opts.get("mapillary_limit", 100),
            download_thumbnails=opts.get("download_thumbnails", True),
            use_cache=opts.get("use_cache", True),
        )

    def plot(self, data: StageData, ax: Axes) -> None:
        from atmosphere.viz import plot_mapillary
        plot_mapillary(data.mapillary_images, ax)


# -----------------------------------------------------------------------------
# Registry — ordered, earliest first
# -----------------------------------------------------------------------------


STAGE_REGISTRY: dict[str, Stage] = {
    "osm": OSMStage(),
    "mapillary": MapillaryStage(),
    # Future: "aligned", "depth", "generated", "evaluation"
}


# Ordering matters for additive rendering. Future stages must be appended
# here in the order they should layer (earlier stage = lower layer).
STAGE_ORDER: list[str] = ["osm", "mapillary"]


def get_stages_up_to(target: str) -> list[Stage]:
    """
    Return all stages up to and including `target`, in order.

    Raises:
        KeyError: if `target` is not a registered stage.
    """
    if target not in STAGE_REGISTRY:
        known = ", ".join(STAGE_ORDER)
        raise KeyError(
            f"Unknown stage '{target}'. Known stages (in order): {known}"
        )
    idx = STAGE_ORDER.index(target)
    return [STAGE_REGISTRY[name] for name in STAGE_ORDER[: idx + 1]]


def list_stages() -> list[tuple[str, str]]:
    """Return (name, description) for every registered stage, in order."""
    return [(name, STAGE_REGISTRY[name].description) for name in STAGE_ORDER]